git add *
set /p DUMMY=Hit ENTER to continue...

git commit -m "Automatic commit by AutoGit"
set /p DUMMY=Hit ENTER to continue...

git pull
set /p DUMMY=Hit ENTER to continue...

git pull upstream master
set /p DUMMY=Hit ENTER to continue...

git push
set /p DUMMY=Hit ENTER to continue...